---
- name: Install EPEL
  yum: name=epel-release state=present

- name: Install nginx
  yum: name=nginx state=present

- name: Install Git
  yum: name=git state=present

- name: Clone repo
  git:
    repo: https://github.com/Josep-Andreu/Optativa-cloud.git
    clone: yes
    dest: ./files/practica1
- name: Copy file to destination
  copy:
    src: ./files/practica1/index.html
    remote_src: true
    dest: /usr/share/nginx/html/index.html
- name: Make index.html accessible
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
- name: Restart
  service: name=nginx state=restarted enabled=yes