apiVersion: v1
kind: Service
metadata:
    name: tomcat
    labels:
        app: tomcat
spec:
    selector:
        app: tomcat
    ports:
        - port: 8080
          targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: tomcat
    name: deploy-tomcat
spec:
    replicas: 4
    selector: 
        matchLabels: 
            app: tomcat
    template:
        metadata: 
            labels:
                app: tomcat
        spec:
            containers:
                - name: tomcat
                  image: tomcat:8-jre8-openjdk
                  ports:
                    - containerPort: 8080
                  volumeMounts:
                    - mountPath: "usr/local/tomcat/webapps"
                      name: tomcat-persistent-storage
                  resources:
                    limits: 
                        memory: "256Mi"
                        cpu: "250m"
            volumes:
            - name: tomcat-persistent-storage
              persistentVolumeClaim:
                claimName: pvc-tomcat
            tolerations:
                - key: "type"
                  operator: "Equal"
                  value: "shared"
                  effect: "NoExecute"